"""add cookies_json and headers_json to accounts

Revision ID: 251c5b2524c6
Revises: 92e4288a9aea
Create Date: 2025-10-30 20:01:48.392104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251c5b2524c6'
down_revision = '92e4288a9aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headers_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('headers_json')

    # ### end Alembic commands ###
