"""add error_message to accounts

Revision ID: 25656149b1f2
Revises: 5c894ae739a8
Create Date: 2025-10-30 23:33:35.292318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25656149b1f2'
down_revision = '5c894ae739a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
