"""add login_failure_type to accounts

Revision ID: 25ac27b6c2ad
Revises: 91871a549f8d
Create Date: 2025-10-31 00:54:24.198356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ac27b6c2ad'
down_revision = '91871a549f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_failure_type', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('login_failure_type')

    # ### end Alembic commands ###
