"""add raw_json to account_year_stats

Revision ID: 5c894ae739a8
Revises: 251c5b2524c6
Create Date: 2025-10-30 20:39:06.235497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c894ae739a8'
down_revision = '251c5b2524c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_year_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_year_stats', schema=None) as batch_op:
        batch_op.drop_column('raw_json')

    # ### end Alembic commands ###
