"""add telegram message ids to accounts

Revision ID: 664bc81b6b69
Revises: 25656149b1f2
Create Date: 2025-10-31 00:11:22.512221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664bc81b6b69'
down_revision = '25656149b1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('after_login_telegram_message_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('stats_status_telegram_message_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('stats_status_telegram_message_id')
        batch_op.drop_column('after_login_telegram_message_id')

    # ### end Alembic commands ###
