"""change telegram message to url format

Revision ID: 91871a549f8d
Revises: 664bc81b6b69
Create Date: 2025-10-31 00:24:12.481130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91871a549f8d'
down_revision = '664bc81b6b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('after_login_telegram_message_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stats_status_telegram_message_url', sa.Text(), nullable=True))
        batch_op.drop_column('after_login_telegram_message_id')
        batch_op.drop_column('stats_status_telegram_message_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stats_status_telegram_message_id', mysql.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('after_login_telegram_message_id', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('stats_status_telegram_message_url')
        batch_op.drop_column('after_login_telegram_message_url')

    # ### end Alembic commands ###
