"""add cookies_json to accounts

Revision ID: 92e4288a9aea
Revises: b7f982ea7934
Create Date: 2025-10-30 18:48:06.990673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e4288a9aea'
down_revision = 'b7f982ea7934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cookies_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('cookies_json')

    # ### end Alembic commands ###
